debian package: missing debhelper part in postinst

diff --git a/debian/metaproxy.postinst b/debian/metaproxy.postinst
--- a/debian/metaproxy.postinst
+++ b/debian/metaproxy.postinst
@@ -66,3 +66,16 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
     fi
 fi
 # End automatically added section
+# Automatically added by dh_installsystemd/13.24.2
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+    if [ -d /run/systemd/system ]; then
+        systemctl --system daemon-reload >/dev/null || true
+        if [ -n "$2" ]; then
+            _dh_action=restart
+        else
+            _dh_action=start
+        fi
+        deb-systemd-invoke $_dh_action 'metaproxy.service' >/dev/null || true
+    fi
+fi
+# End automatically added section
