Use systemd on Debian (#60)

diff --git a/debian/metaproxy.postinst b/debian/metaproxy.postinst
--- a/debian/metaproxy.postinst
+++ b/debian/metaproxy.postinst
@@ -4,18 +4,22 @@ set -e
 
 case "$1" in
     configure)
-    . /etc/metaproxy/metaproxy.user
-    
-    # 1. create group if not existing
+    . /etc/default/metaproxy
+
+    # remove old init.d script if existing
+    if [ -f /etc/init.d/metaproxy ]; then
+        rm -f /etc/init.d/metaproxy
+    fi
+    # create group if not existing
     if ! getent group | grep -q "^$SERVER_GROUP:" ; then
         echo -n "Adding group $SERVER_GROUP.."
         addgroup --quiet --system $SERVER_GROUP 2>/dev/null ||true
         echo "..done"
     fi
-    # 2. create homedir if not existing
+    # create homedir if not existing
     test -d $SERVER_HOME || mkdir $SERVER_HOME
 
-    # 3. create user if not existing
+    # create user if not existing
     if ! getent passwd | grep -q "^$SERVER_USER:"; then
         echo -n "Adding system user $SERVER_USER.."
         adduser --quiet \
@@ -26,23 +30,39 @@ case "$1" in
             $SERVER_USER 2>/dev/null || true
         echo "..done"
     fi
-    # 4. adjust passwd entry
+    # adjust passwd entry
     usermod -c "$SERVER_NAME" \
         -d $SERVER_HOME   \
         -g $SERVER_GROUP  \
         $SERVER_USER
-    
-    # 5. adjust file and directory permissions
+
+    # adjust file and directory permissions
     if ! dpkg-statoverride --list $SERVER_HOME >/dev/null
     then
         chown -R $SERVER_USER:adm $SERVER_HOME
         chmod u=rwx,g=rxs,o= $SERVER_HOME
     fi
-
-    # 6. start service
-    if [ -x "/etc/init.d/metaproxy" ]; then
-        update-rc.d metaproxy defaults >/dev/null
-        invoke-rc.d metaproxy start || exit $?
+    # reload systemd daemon if systemd is used
+    if [ -d /run/systemd/system ]; then
+        systemctl daemon-reload || true
     fi
     ;;
 esac
+
+# Automatically added by dh_installsystemd/13.24.2
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+    # The following line should be removed in trixie or trixie+1
+    deb-systemd-helper unmask 'metaproxy.service' >/dev/null || true
+
+    # was-enabled defaults to true, so new installations run enable.
+    if deb-systemd-helper --quiet was-enabled 'metaproxy.service'; then
+        # Enables the unit on first installation, creates new
+        # symlinks on upgrades if the unit file has changed.
+        deb-systemd-helper enable 'metaproxy.service' >/dev/null || true
+    else
+        # Update the statefile to add new symlinks (if any), which need to be
+        # cleaned up on purge. Also remove old symlinks.
+    deb-systemd-helper update-state 'metaproxy.service' >/dev/null || true
+    fi
+fi
+# End automatically added section
